services:
  - type: web
    name: ad-free-yt-download
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    disk:
      name: downloads-disk
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1
